apiVersion: apps/v1
kind: Deployment
metadata:
  name: krish
  labels:
          app: krish
spec:
  replicas: 4
  selector:
    matchLabels:
       app: krish
  template:
     metadata:
       labels:
         app: krish
     spec:
        containers:
        - name: krish-con
          image: revakrish/revakrish-devopsclass-set:01082024
          ports:
          - containerPort: 8080
       
---
apiVersion: v1
kind: Service
metadata:
  name: krish
  labels:
    app: krish
spec:
  selector:
    app: krish
  type: NodePort
  ports:
  - nodePort: 32200
    port: 8080
    targetPort: 8080
